import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
// import Card from '../components/Card'
import shirt2 from '../assets/shirt2.jpg'
import { EditOutlined, EllipsisOutlined, SettingOutlined, ShoppingCartOutlined, HeartOutlined, HeartFilled } from '@ant-design/icons';
import { Avatar, Card } from 'antd';
import heroImage from '../assets/hero_image.webp'
import toast from 'react-hot-toast';
import ScrollButton from '../components/ScrollButton';
import { BackTop } from 'antd';
import { ArrowUpOutlined } from '@ant-design/icons';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import axios from 'axios';
import Loader from '../components/Loader';

const { Meta } = Card;

export default function Home() {

  const [data, setData] = useState(null);
  const [userFav, setUserFav] = useState(null);
  const [loading, setLoading] = useState(true);

  const toastSuccess = () => {
    toast.success('ADD TO CART SUCCESS ',
      {
        // icon: '😝',
        style: {
          borderRadius: '10px',
          padding: "1rem",
          fontWeight: "bold",
          // fontSize: "1.5rem"
        },
      });
    console.log("TOASTTs");
  }

  const toastFavSuccess = (props) => {
    axios.post(`http://localhost:5000/api/FavoriteItem/Test`, {
      itemID: props
    }).then((res) => {
      console.log(res);
      console.log(res.data);
    })

    console.log('FAV ' + props);
    // fetchFav();
    console.log(userFav);
    toast.success('ADD TO CART SUCCESS ',
      {
        icon: '❤️',
        style: {
          borderRadius: '10px',
          padding: "1rem",
          fontWeight: "bold",
          // fontSize: "1.5rem"
        },
      });
  }

  const delFavSuccess = (props) => {
    axios.delete(`http://localhost:5000/api/FavoriteItem/Test`, {
      data: {
        itemID: props
      }
    }).then((res) => {
      console.log(res);
      console.log(res.data);
    })

    console.log('UNFAV ' + props);
    // fetchFav();
    console.log(userFav);

    toast.success('DELETE FROM FAV SUCCESS ',
      {
        icon: '✖',
        style: {
          borderRadius: '10px',
          padding: "1rem",
          fontWeight: "bold",
          // fontSize: "1.5rem"
        },
      });
  }

  const fetchData = async () => {
    const response1 = await axios.get('http://localhost:5000/api/Items');
    const response2 = await axios.get('http://localhost:5000/api/FavoriteItem/Test');

    setData(response1.data);
    setUserFav(response2.data);
    setLoading(false);
    console.log(data);
    console.log(userFav);
  }
  useEffect(() => {

    fetchData();

    // axios.get('http://localhost:5000/api/Items').then(res => {
    //   // console.log('item',res.data);
    //   setData(res.data);
    //   console.log('data', data);
    // }).catch((err) => {
    //   console.log(err);
    // })

  }, [])

  if (loading) {
    //loading on slow internet
    return <>
      <main className={styles.main}>
        <div className={styles.spinner}><Loader /></div>
      </main>
    </>
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>KU E-SHOP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <style>
          @import url('https://fonts.googleapis.com/css2?family=Roboto&display=swap');
        </style>
      </Head>


      <main className={styles.main}>

        <div className={styles.firstColumn}>

          <div className={styles.column}>
            <h1 className={styles.title}>
              Fast Shipping on Orders $99+
            </h1>

            <h1 className={styles.secondTitle}>
              Within the United States Only
            </h1>
          </div>

          <div className={styles.blackLine} />

          <div className={styles.column}>

            <h1 className={styles.title}>
              Quick Pickup
            </h1>
            <h1 className={styles.secondTitle}>
              Buy Online, Pickup In store
            </h1>
          </div>
          <div className={styles.blackLine} />

          <div className={styles.column}>


            <h1 className={styles.title}>
              Worldwide Shipping
            </h1>
            <h1 className={styles.secondTitle}>
              Easy Ship with Glopal
            </h1>
          </div>
        </div>


        <div className={styles.hero_section}>

          <div className={styles.hero_image}>
            <Image src={heroImage} alt="shirt" layout='responsive' />

          </div>
          <p className={styles.description}>
            WELCOME TO OUR STORE
          </p>


        </div>

        <div className={styles.grid}>


          {data && data.map((item) => {
            // console.log('item',item);
            return (
              <Card
                hoverable
                style={{
                  width: 300,
                  marginRight: "2rem",
                  marginTop: "1rem"
                }}
                cover={
                  <Link href={`/product/${item._id}`}>
                    <img
                      alt="example"
                      src={item.imagePath}
                      className='test'
                      style={{ borderRadius: "2px 2px 0 0", width: "90%", marginLeft: "1rem", marginTop: "1rem" }}
                    />
                  </Link>
                }
                actions={[
                  <>
                    {
                      !(userFav.includes(item._id))
                        ? <HeartOutlined onClick={() => toastFavSuccess(item._id)} key="edit" style={{ fontSize: '16px', color: '#E80F88', }} />
                        : <HeartFilled onClick={() => delFavSuccess(item._id)} style={{ fontSize: '16px', color: '#E80F88', }} key="edit" />
                    }
                  </>,
                  // <HeartFilled style={{ fontSize: '16px', color: '#E80F88', }} key="edit" />,
                  <ShoppingCartOutlined key="setting" style={{ fontSize: '20px' }} onClick={toastSuccess} />,
                  <EllipsisOutlined key="ellipsis" style={{ fontSize: '20px' }} />,
                ]}
              >
                <Meta
                  title={item.name}
                  description={item.price}
                />
              </Card>
            )
          })}


          {/* <Link href={`/product/$test`}>
            <Card
              hoverable
              style={{
                width: 300,
                marginRight: "2rem",
                marginTop: "1rem"
              }}
              cover={
                <img
                  alt="example"
                  src="https://seekthailand.com/uploads/products/b54e058785bd1b0893fd2f1138a312bb.jpg"
                  className='test'
                  style={{ borderRadius: "2px 2px 0 0", width: "90%", marginLeft: "1rem", marginTop: "1rem" }}
                />
              }
              actions={[
                <>
                  {
                    true ? <HeartOutlined key="edit" style={{ fontSize: '16px', color: '#E80F88', }} /> : <HeartFilled style={{ fontSize: '16px', color: '#E80F88', }} key="edit" />
                  }
                </>,
                // <HeartFilled style={{ fontSize: '16px', color: '#E80F88', }} key="edit" />,
                <ShoppingCartOutlined key="setting" style={{ fontSize: '20px' }} onClick={toastSuccess} />,
                <EllipsisOutlined key="ellipsis" style={{ fontSize: '20px' }} />,
              ]}
            >
              <Meta
                title="Men Long sleeves white"
                description="699 THB"
              />
            </Card>
          </Link>



          <Card
            hoverable
            style={{
              width: 300,
              marginRight: "2rem",
              marginTop: "1rem"

            }}
            cover={
              <img
                alt="example"
                src="https://seekthailand.com/uploads/products/57b191e9d5f8900b48cbb8c35a747dc9.jpg"
                style={{ borderRadius: "2px 2px 0 0", width: "90%", marginLeft: "1rem", marginTop: "1rem" }}
              />
            }
            actions={[
              <>
                {
                  true ? <HeartOutlined key="edit" style={{ fontSize: '16px', color: '#E80F88', }} /> : <HeartFilled style={{ fontSize: '16px', color: '#E80F88', }} key="edit" />
                }
              </>,
              <ShoppingCartOutlined key="setting" style={{ fontSize: '20px' }} onClick={toastSuccess} />,
              <EllipsisOutlined key="ellipsis" style={{ fontSize: '20px' }} />,
            ]}
          >
            <Meta
              title="Men white sneaker"
              description="1299 THB"
            />
          </Card>

          <Card
            hoverable
            style={{
              width: 300,
              marginRight: "2rem",
              marginTop: "1rem"

            }}
            cover={
              <img
                alt="example"
                src="https://seekthailand.com/uploads/products/cf2f387137a7b5dbcaf85bc4f80c66d7.jpg"
                style={{ borderRadius: "2px 2px 0 0", width: "90%", marginLeft: "1rem", marginTop: "1rem" }}
              />
            }
            actions={[
              <>
                {
                  false ? <HeartOutlined key="edit" style={{ fontSize: '16px', color: '#E80F88', }} /> : <HeartFilled style={{ fontSize: '16px', color: '#E80F88', }} key="edit" />
                }
              </>,
              <ShoppingCartOutlined key="setting" style={{ fontSize: '20px' }} onClick={toastSuccess} />,
              <EllipsisOutlined key="ellipsis" style={{ fontSize: '20px' }} />,
            ]}
          >
            <Meta
              title="Men Long sleeves yellow"
              description="1299 THB"
            />
          </Card>

          <Card
            hoverable
            style={{
              width: 300,
              marginRight: "2rem",
              marginTop: "1rem"

            }}
            cover={
              <img
                alt="example"
                src="https://seekthailand.com/uploads/products/c2d928be82e2c28c936b6674168cf051.jpg"
                style={{ borderRadius: "2px 2px 0 0", width: "90%", marginLeft: "1rem", marginTop: "1rem" }}
              />
            }
            actions={[
              <>
                {
                  true ? <HeartOutlined key="edit" style={{ fontSize: '16px', color: '#E80F88', }} /> : <HeartFilled style={{ fontSize: '16px', color: '#E80F88', }} key="edit" />
                }
              </>,
              <ShoppingCartOutlined key="setting" style={{ fontSize: '20px' }} onClick={toastSuccess} />,
              <EllipsisOutlined key="ellipsis" style={{ fontSize: '20px' }} />,
            ]}
          >
            <Meta
              title="Men Long sleeves black"
              description="1299 THB"
            />
          </Card>
          <Card
            hoverable
            style={{
              width: 300,
              marginRight: "2rem",
              marginTop: "1rem"
            }}
            cover={
              <img
                alt="example"
                src="https://seekthailand.com/uploads/products/ee61f85ffad46a97936e8f9101f2a54c.jpg"
                className='test'
                style={{ borderRadius: "2px 2px 0 0", width: "90%", marginLeft: "1rem", marginTop: "1rem" }}
              />
            }
            actions={[
              <>
                {
                  true ? <HeartOutlined key="edit" style={{ fontSize: '16px', color: '#E80F88', }} /> : <HeartFilled style={{ fontSize: '16px', color: '#E80F88', }} key="edit" />
                }
              </>,
              <ShoppingCartOutlined key="setting" style={{ fontSize: '20px' }} onClick={toastSuccess} />,
              <EllipsisOutlined key="ellipsis" style={{ fontSize: '20px' }} />,
            ]}
          >
            <Meta
              title="Men black sneaker"
              description="699 THB"
            />
          </Card>

          <Card
            hoverable
            style={{
              width: 300,
              marginRight: "2rem",
              marginTop: "1rem"

            }}
            cover={
              <img
                alt="example"
                src="https://seekthailand.com/uploads/products/ead69040aa8297a8535b5ce07cea5271.jpg"
                style={{ borderRadius: "2px 2px 0 0", width: "90%", marginLeft: "1rem", marginTop: "1rem" }}
              />
            }
            actions={[
              <>
                {
                  true ? <HeartOutlined key="edit" style={{ fontSize: '16px', color: '#E80F88', }} /> : <HeartFilled style={{ fontSize: '16px', color: '#E80F88', }} key="edit" />
                }
              </>,
              <ShoppingCartOutlined key="setting" style={{ fontSize: '20px' }} onClick={toastSuccess} />,
              <EllipsisOutlined key="ellipsis" style={{ fontSize: '20px' }} />,
            ]}
          >
            <Meta
              title="Men white red sneaker"
              description="1299 THB"
            />
          </Card>

          <Card
            hoverable
            style={{
              width: 300,
              marginRight: "2rem",
              marginTop: "1rem"

            }}
            cover={
              <img
                alt="example"
                src="https://seekthailand.com/uploads/products/183da5871f2b39c02dd19cc346e597fc.jpg"
                style={{ borderRadius: "2px 2px 0 0", width: "90%", marginLeft: "1rem", marginTop: "1rem" }}
              />
            }
            actions={[
              <>
                {
                  true ? <HeartOutlined key="edit" style={{ fontSize: '16px', color: '#E80F88', }} /> : <HeartFilled style={{ fontSize: '16px', color: '#E80F88', }} key="edit" />
                }
              </>,
              <ShoppingCartOutlined key="setting" style={{ fontSize: '20px' }} onClick={toastSuccess} />,
              <EllipsisOutlined key="ellipsis" style={{ fontSize: '20px' }} />,
            ]}
          >
            <Meta
              title="Men trouser red"
              description="1299 THB"
            />
          </Card>

          <Card
            hoverable
            style={{
              width: 300,
              marginRight: "2rem",
              marginTop: "1rem"

            }}
            cover={
              <img
                alt="example"
                src="https://seekthailand.com/uploads/products/b6bafb992ecaaaf8a5c44dcb95d1fdbe.jpg"
                style={{ borderRadius: "2px 2px 0 0", width: "90%", marginLeft: "1rem", marginTop: "1rem" }}
              />
            }
            actions={[
              <>
                {
                  true ? <HeartOutlined key="edit" style={{ fontSize: '16px', color: '#E80F88', }} /> : <HeartFilled style={{ fontSize: '16px', color: '#E80F88', }} key="edit" />
                }
              </>,
              <ShoppingCartOutlined key="setting" style={{ fontSize: '20px' }} onClick={toastSuccess} />,
              <EllipsisOutlined key="ellipsis" style={{ fontSize: '20px' }} />,
            ]}
          >
            <Meta
              title="Men basketball purple"
              description="1299 THB"
            />
          </Card>
          <Card
            hoverable
            style={{
              width: 300,
              marginRight: "2rem",
              marginTop: "1rem"
            }}
            cover={
              <img
                alt="example"
                src="https://seekthailand.com/uploads/products/eaae5f0c98b2e66acc4d154ab6c85435.jpg"
                className='test'
                style={{ borderRadius: "2px 2px 0 0", width: "90%", marginLeft: "1rem", marginTop: "1rem" }}
              />
            }
            actions={[
              <>
                {
                  true ? <HeartOutlined key="edit" style={{ fontSize: '16px', color: '#E80F88', }} /> : <HeartFilled style={{ fontSize: '16px', color: '#E80F88', }} key="edit" />
                }
              </>,
              <ShoppingCartOutlined key="setting" style={{ fontSize: '20px' }} onClick={toastSuccess} />,
              <EllipsisOutlined key="ellipsis" style={{ fontSize: '20px' }} />,
            ]}
          >
            <Meta
              title="Men basketball black"
              description="699 THB"
            />
          </Card>

          <Card
            hoverable
            style={{
              width: 300,
              marginRight: "2rem",
              marginTop: "1rem"

            }}
            cover={
              <img
                alt="example"
                src="https://seekthailand.com/uploads/products/703f97dcc1610b9e4a99c8db87fae0a7.jpg"
                style={{ borderRadius: "2px 2px 0 0", width: "90%", marginLeft: "1rem", marginTop: "1rem" }}
              />
            }
            actions={[
              <>
                {
                  true ? <HeartOutlined key="edit" style={{ fontSize: '16px', color: '#E80F88', }} /> : <HeartFilled style={{ fontSize: '16px', color: '#E80F88', }} key="edit" />
                }
              </>,
              <ShoppingCartOutlined key="setting" style={{ fontSize: '20px' }} onClick={toastSuccess} />,
              <EllipsisOutlined key="ellipsis" style={{ fontSize: '20px' }} />,
            ]}
          >
            <Meta
              title="Men basketball red"
              description="1299 THB"
            />
          </Card>

          <Card
            hoverable
            style={{
              width: 300,
              marginRight: "2rem",
              marginTop: "1rem"

            }}
            cover={
              <img
                alt="example"
                src="https://seekthailand.com/uploads/products/4b8c9842808a0b9749ac262ba3b017dd.jpg"
                style={{ borderRadius: "2px 2px 0 0", width: "90%", marginLeft: "1rem", marginTop: "1rem" }}
              />
            }
            actions={[
              <>
                {
                  true ? <HeartOutlined key="edit" style={{ fontSize: '16px', color: '#E80F88', }} /> : <HeartFilled style={{ fontSize: '16px', color: '#E80F88', }} key="edit" />
                }
              </>,
              <ShoppingCartOutlined key="setting" style={{ fontSize: '20px' }} onClick={toastSuccess} />,
              <EllipsisOutlined key="ellipsis" style={{ fontSize: '20px' }} />,
            ]}
          >
            <Meta
              title="Men basketball blue"
              description="1299 THB"
            />
          </Card>

          <Card
            hoverable
            style={{
              width: 300,
              marginRight: "2rem",
              marginTop: "1rem"

            }}
            cover={
              <img
                alt="example"
                src="https://seekthailand.com/uploads/products/62a3af7f728f751a85362e826bcdddde.jpg"
                style={{ borderRadius: "2px 2px 0 0", width: "90%", marginLeft: "1rem", marginTop: "1rem" }}
              />
            }
            actions={[
              <>
                {
                  true ? <HeartOutlined key="edit" style={{ fontSize: '16px', color: '#E80F88', }} /> : <HeartFilled style={{ fontSize: '16px', color: '#E80F88', }} key="edit" />
                }
              </>,
              <ShoppingCartOutlined key="setting" style={{ fontSize: '20px' }} onClick={toastSuccess} />,
              <EllipsisOutlined key="ellipsis" style={{ fontSize: '20px' }} />,
            ]}
          >
            <Meta
              title="Men white red blue basketball shirt"
              description="1299 THB"
            />
          </Card> */}

        </div>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          SHOPPING PROJECT BY Jittipon Kumurai and Chanwit Jampa
        </a>
      </footer>
      {/* <ScrollButton /> */}
      <BackTop >
        <ArrowUpOutlined
          style={{
            display: 'flex',
            color: "white", fontSize: "1.5rem", position: "fixed", bottom: "40px", zIndex: "1", left: "95%", backgroundColor: "black", borderRadius: "10%", width: "40px", height: "40px", justifyContent: "center", alignItems: "center"
          }} />
      </BackTop>
    </div>
  )
}
