import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
// import Card from '../components/Card'
import shirt2 from '../assets/shirt2.jpg'
import 'antd/dist/antd.css';
import { EditOutlined, EllipsisOutlined, SettingOutlined, ShoppingCartOutlined, HeartOutlined } from '@ant-design/icons';
import { Avatar, Card } from 'antd';
import Navbar from '../components/Navbar';

const { Meta } = Card;


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>KU E-SHOP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main className={styles.main}>
        <h1 className={styles.title}>
          KU E-SHOP
        </h1>

        <p className={styles.description}>
          WELCOME to our STORE
        </p>

        <div className={styles.grid}>
          {/* <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation </h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a> */}

          <Card
            hoverable
            style={{
              width: 300,
              marginRight: "2rem",
              marginTop: "1rem"
            }}
            cover={
              <img
                alt="example"
                src="https://seekthailand.com/uploads/products/b54e058785bd1b0893fd2f1138a312bb.jpg"
                className='test'
                style={{borderRadius:"2px 2px 0 0",width:"90%",marginLeft:"1rem",marginTop:"1rem"}}
              />
            }
            actions={[
              <HeartOutlined key="edit" />,
              <ShoppingCartOutlined key="setting" />,
              <EllipsisOutlined key="ellipsis" />,
            ]}
          >
            <Meta
              title="Men Long sleeves white"
              description="699 THB"
            />
          </Card>

          <Card
            hoverable
            style={{
              width: 300,
              marginRight: "2rem",
              marginTop: "1rem"

            }}
            cover={
              <img
                alt="example"
                src="https://seekthailand.com/uploads/products/57b191e9d5f8900b48cbb8c35a747dc9.jpg"
                style={{borderRadius:"2px 2px 0 0",width:"90%",marginLeft:"1rem",marginTop:"1rem"}}
              />
            }
            actions={[
              <HeartOutlined key="edit" />,
              <ShoppingCartOutlined key="setting" />,
              <EllipsisOutlined key="ellipsis" />,
            ]}
          >
            <Meta
              title="Men white sneaker"
              description="1299 THB"
            />
          </Card>

          <Card
            hoverable
            style={{
              width: 300,
              marginRight: "2rem",
              marginTop: "1rem"

            }}
            cover={
              <img
                alt="example"
                src="https://seekthailand.com/uploads/products/cf2f387137a7b5dbcaf85bc4f80c66d7.jpg"
                style={{borderRadius:"2px 2px 0 0",width:"90%",marginLeft:"1rem",marginTop:"1rem"}}
              />
            }
            actions={[
              <HeartOutlined key="edit" />,
              <ShoppingCartOutlined key="setting" />,
              <EllipsisOutlined key="ellipsis" />,
            ]}
          >
            <Meta
              title="Men white sneaker"
              description="1299 THB"
            />
          </Card>

          <Card
            hoverable
            style={{
              width: 300,
              marginRight: "2rem",
              marginTop: "1rem"

            }}
            cover={
              <img
                alt="example"
                src="https://seekthailand.com/uploads/products/c2d928be82e2c28c936b6674168cf051.jpg"
                style={{borderRadius:"2px 2px 0 0",width:"90%",marginLeft:"1rem",marginTop:"1rem"}}
              />
            }
            actions={[
              <HeartOutlined key="edit" />,
              <ShoppingCartOutlined key="setting" />,
              <EllipsisOutlined key="ellipsis" />,
            ]}
          >
            <Meta
              title="Men white sneaker"
              description="1299 THB"
            />
          </Card>
          <Card
            hoverable
            style={{
              width: 300,
              marginRight: "2rem",
              marginTop: "1rem"
            }}
            cover={
              <img
                alt="example"
                src="https://seekthailand.com/uploads/products/b54e058785bd1b0893fd2f1138a312bb.jpg"
                className='test'
                style={{borderRadius:"2px 2px 0 0",width:"90%",marginLeft:"1rem",marginTop:"1rem"}}
              />
            }
            actions={[
              <HeartOutlined key="edit" />,
              <ShoppingCartOutlined key="setting" />,
              <EllipsisOutlined key="ellipsis" />,
            ]}
          >
            <Meta
              title="Men Long sleeves white"
              description="699 THB"
            />
          </Card>

          <Card
            hoverable
            style={{
              width: 300,
              marginRight: "2rem",
              marginTop: "1rem"

            }}
            cover={
              <img
                alt="example"
                src="https://seekthailand.com/uploads/products/57b191e9d5f8900b48cbb8c35a747dc9.jpg"
                style={{borderRadius:"2px 2px 0 0",width:"90%",marginLeft:"1rem",marginTop:"1rem"}}
              />
            }
            actions={[
              <HeartOutlined key="edit" />,
              <ShoppingCartOutlined key="setting" />,
              <EllipsisOutlined key="ellipsis" />,
            ]}
          >
            <Meta
              title="Men white sneaker"
              description="1299 THB"
            />
          </Card>

          <Card
            hoverable
            style={{
              width: 300,
              marginRight: "2rem",
              marginTop: "1rem"

            }}
            cover={
              <img
                alt="example"
                src="https://seekthailand.com/uploads/products/cf2f387137a7b5dbcaf85bc4f80c66d7.jpg"
                style={{borderRadius:"2px 2px 0 0",width:"90%",marginLeft:"1rem",marginTop:"1rem"}}
              />
            }
            actions={[
              <HeartOutlined key="edit" />,
              <ShoppingCartOutlined key="setting" />,
              <EllipsisOutlined key="ellipsis" />,
            ]}
          >
            <Meta
              title="Men white sneaker"
              description="1299 THB"
            />
          </Card>

          <Card
            hoverable
            style={{
              width: 300,
              marginRight: "2rem",
              marginTop: "1rem"

            }}
            cover={
              <img
                alt="example"
                src="https://seekthailand.com/uploads/products/c2d928be82e2c28c936b6674168cf051.jpg"
                style={{borderRadius:"2px 2px 0 0",width:"90%",marginLeft:"1rem",marginTop:"1rem"}}
              />
            }
            actions={[
              <HeartOutlined key="edit" />,
              <ShoppingCartOutlined key="setting" />,
              <EllipsisOutlined key="ellipsis" />,
            ]}
          >
            <Meta
              title="Men white sneaker"
              description="1299 THB"
            />
          </Card>
          <Card
            hoverable
            style={{
              width: 300,
              marginRight: "2rem",
              marginTop: "1rem"
            }}
            cover={
              <img
                alt="example"
                src="https://seekthailand.com/uploads/products/b54e058785bd1b0893fd2f1138a312bb.jpg"
                className='test'
                style={{borderRadius:"2px 2px 0 0",width:"90%",marginLeft:"1rem",marginTop:"1rem"}}
              />
            }
            actions={[
              <HeartOutlined key="edit" />,
              <ShoppingCartOutlined key="setting" />,
              <EllipsisOutlined key="ellipsis" />,
            ]}
          >
            <Meta
              title="Men Long sleeves white"
              description="699 THB"
            />
          </Card>

          <Card
            hoverable
            style={{
              width: 300,
              marginRight: "2rem",
              marginTop: "1rem"

            }}
            cover={
              <img
                alt="example"
                src="https://seekthailand.com/uploads/products/57b191e9d5f8900b48cbb8c35a747dc9.jpg"
                style={{borderRadius:"2px 2px 0 0",width:"90%",marginLeft:"1rem",marginTop:"1rem"}}
              />
            }
            actions={[
              <HeartOutlined key="edit" />,
              <ShoppingCartOutlined key="setting" />,
              <EllipsisOutlined key="ellipsis" />,
            ]}
          >
            <Meta
              title="Men white sneaker"
              description="1299 THB"
            />
          </Card>

          <Card
            hoverable
            style={{
              width: 300,
              marginRight: "2rem",
              marginTop: "1rem"

            }}
            cover={
              <img
                alt="example"
                src="https://seekthailand.com/uploads/products/cf2f387137a7b5dbcaf85bc4f80c66d7.jpg"
                style={{borderRadius:"2px 2px 0 0",width:"90%",marginLeft:"1rem",marginTop:"1rem"}}
              />
            }
            actions={[
              <HeartOutlined key="edit" />,
              <ShoppingCartOutlined key="setting" />,
              <EllipsisOutlined key="ellipsis" />,
            ]}
          >
            <Meta
              title="Men white sneaker"
              description="1299 THB"
            />
          </Card>

          <Card
            hoverable
            style={{
              width: 300,
              marginRight: "2rem",
              marginTop: "1rem"

            }}
            cover={
              <img
                alt="example"
                src="https://seekthailand.com/uploads/products/c2d928be82e2c28c936b6674168cf051.jpg"
                style={{borderRadius:"2px 2px 0 0",width:"90%",marginLeft:"1rem",marginTop:"1rem"}}
              />
            }
            actions={[
              <HeartOutlined key="edit" />,
              <ShoppingCartOutlined key="setting" />,
              <EllipsisOutlined key="ellipsis" />,
            ]}
          >
            <Meta
              title="Men white sneaker"
              description="1299 THB"
            />
          </Card>

          {/* <Card title={"KU T-Shirt"} description={"KU T-Shirt"} image={"../assets/shirt2.jpg"} link={"https://www.ku.ac.th/th"}/> */}
          {/* <Image src={shirt2} alt="KU T-Shirt" width={500} height={500} /> */}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
